################################################################################
#
# gnuradio
#
################################################################################

GNURADIO310_VERSION = 3.10.4.0
GNURADIO310_SITE = $(call github,gnuradio,gnuradio,v$(GNURADIO_VERSION))
GNURADIO310_LICENSE = GPL-3.0+
GNURADIO310_LICENSE_FILES = COPYING

GNURADIO310_SUPPORTS_IN_SOURCE_BUILD = NO

GNURADIO310_DEPENDENCIES = \
	host-python3 \
	boost \
	log4cpp \
	gmp \
	spdlog \
	volk

GNURADIO310_CONF_OPTS = \
	-DPYTHON_EXECUTABLE=$(HOST_DIR)/bin/python3 \
	-DENABLE_DEFAULT=OFF \
	-DENABLE_VOLK=ON \
	-DENABLE_GNURADIO_RUNTIME=ON \
	-DENABLE_INTERNAL_VOLK=OFF \
	-DENABLE_TESTING=OFF \
	-DXMLTO_EXECUTABLE=NOTFOUND

# For third-party blocks, the gnuradio libraries are mandatory at
# compile time.
GNURADIO310_INSTALL_STAGING = YES

ifeq ($(BR2_TOOLCHAIN_HAS_LIBATOMIC),y)
GNURADIO310_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS=-latomic
endif

ifeq ($(BR2_PACKAGE_ORC),y)
GNURADIO310_DEPENDENCIES += orc
GNURADIO310_CONF_OPTS += -DENABLE_ORC=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_ORC=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_ANALOG),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_ANALOG=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_ANALOG=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_AUDIO),y)
ifeq ($(BR2_PACKAGE_ALSA_LIB),y)
GNURADIO310_DEPENDENCIES += alsa-lib
endif
ifeq ($(BR2_PACKAGE_PORTAUDIO),y)
GNURADIO310_DEPENDENCIES += portaudio
endif
GNURADIO310_CONF_OPTS += -DENABLE_GR_AUDIO=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_AUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_BLOCKS),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_BLOCKS=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_BLOCKS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_CHANNELS),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_CHANNELS=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_CHANNELS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_CTRLPORT),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_CTRLPORT=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_CTRLPORT=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_DIGITAL),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_DIGITAL=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_DIGITAL=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_DTV),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_DTV=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_DTV=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_FEC),y)
GNURADIO310_DEPENDENCIES += gsl
GNURADIO310_CONF_OPTS += -DENABLE_GR_FEC=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_FEC=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_FFT),y)
GNURADIO310_DEPENDENCIES += fftw-single
GNURADIO310_CONF_OPTS += -DENABLE_GR_FFT=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_FFT=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_FILTER),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_FILTER=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_FILTER=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_PYTHON),y)
GNURADIO310_DEPENDENCIES += python3 python-pybind \
	host-python-numpy host-python-packaging
GNURADIO310_CONF_OPTS += -DENABLE_PYTHON=ON
# mandatory to install python modules in site-packages and to use
# correct path for python libraries
GNURADIO310_CONF_OPTS += -DGR_PYTHON_RELATIVE=ON \
	-DGR_PYTHON_DIR=lib/python$(PYTHON3_VERSION_MAJOR)/site-packages
else
GNURADIO310_CONF_OPTS += -DENABLE_PYTHON=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_QTGUI),y)
GNURADIO310_DEPENDENCIES += qt5base python-pyqt5 qwt
GNURADIO310_CONF_OPTS += -DENABLE_GR_QTGUI=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_QTGUI=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_TRELLIS),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_TRELLIS=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_TRELLIS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_UHD),y)
GNURADIO310_DEPENDENCIES += uhd
GNURADIO310_CONF_OPTS += -DENABLE_GR_UHD=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_UHD=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_UTILS),y)
GNURADIO310_CONF_OPTS += -DENABLE_GR_UTILS=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_UTILS=OFF
endif

ifeq ($(BR2_PACKAGE_GNURADIO310_ZEROMQ),y)
GNURADIO310_DEPENDENCIES += cppzmq
ifeq ($(BR2_PACKAGE_GNURADIO310_PYTHON),y)
GNURADIO310_DEPENDENCIES += python-pyzmq
endif
GNURADIO310_CONF_OPTS += -DENABLE_GR_ZEROMQ=ON
else
GNURADIO310_CONF_OPTS += -DENABLE_GR_ZEROMQ=OFF
endif

$(eval $(cmake-package))
